service: gdc-rating

stage: dev
region: us-east-1

provider:
  name: aws
  runtime: nodejs6.10

package:
  individually: true
  exclude:
    - README.md
    - package.json
    - app.js
    - functions/**
    - includes/**

functions:

  findone:
    handler: functions/findone/findone.findone
    events:
      - http:
          method: get
          path: hello
    package:
      include:
        - functions/findone/**
        - includes/utils.js
