service: gdc-rating

stage: dev
region: us-east-1

provider:
  name: aws
  runtime: nodejs6.10

package:
  individually: true
  exclude:
    - README.md
    - package.json
    - app.js
    - functions/**
    - includes/**

functions:

  findone:
    handler: functions/findone/findone.findone
    events:
      - http:
          method: get
          path: findOne
    package:
      include:
        - functions/findone/**
        - includes/utils.js
        - includes/config.json

  findbulk:
    handler: functions/findbulk/findbulk.findbulk
    events:
      - http:
          method: post
          path: findBulk
    package:
      include:
        - functions/findbulk/**
        - includes/utils.js
        - includes/config.json

  findtoprated:
    handler: functions/findtoprated/findtoprated.findtoprated
    events:
      - http:
          method: get
          path: findTopRated
    package:
      include:
        - functions/findtoprated/**
        - includes/utils.js
        - includes/config.json

  vote:
    handler: functions/vote/vote.vote
    events:
      - http:
          method: post
          path: vote
    package:
      include:
        - functions/vote/**
        - includes/utils.js
        - includes/config.json
